added shared-cosmos feature

diff --git a/edit-secrets b/edit-secrets
--- a/edit-secrets
+++ b/edit-secrets
@@ -23,18 +23,18 @@ test -d /dev/shm && export TMPDIR='/dev/shm'
 TMPFILE=$(mktemp edit-secrets.XXXXXXXXXX)
 TMPFILE2=$(mktemp edit-secrets.XXXXXXXXXX)
 
-if [ ! -f $TMPFILE ]; then
+if [ ! -f "$TMPFILE" ]; then
     echo "$TMPFILE"
     echo "$0: Failed creating temporary file"
     exit 1
 fi
-if [ ! -f $TMPFILE2 ]; then
+if [ ! -f "$TMPFILE2" ]; then
     echo "$TMPFILE2"
     echo "$0: Failed creating temporary file 2"
     exit 1
 fi
 
-trap "rm -f $TMPFILE $TMPFILE2" EXIT
+trap 'rm -f "$TMPFILE" "$TMPFILE2"' EXIT
 
 
 if [[ ! $1 ]]; then
@@ -112,6 +112,7 @@ function edit_copy_and_commit()
     # This code runs on the administrators local machine
     #
     local host=$1
+    local global=$2
 
     if [[ ${EDITOR} ]]; then
 	declare -r REMOTE_EDITOR="${EDITOR}"
@@ -120,29 +121,33 @@ function edit_copy_and_commit()
     fi
 
     # Execute this script, on a remote host
-    ssh -t root@"${host}" EDITOR="${REMOTE_EDITOR}" /var/cache/cosmos/repo/edit-secrets --on-host
-    scp -q root@"${host}:${LAST_OUTPUT_FILENAME}" ${TMPFILE}
+    ssh -t root@"${host}" EDITOR="${REMOTE_EDITOR}" /var/cache/cosmos/repo/edit-secrets --on-host "$global"
+    scp -q root@"${host}:${LAST_OUTPUT_FILENAME}" "${TMPFILE}"
 
     local save_to
-    if grep ^"STATUS=UPDATED" $TMPFILE > /dev/null; then
+    if grep ^"STATUS=UPDATED" "$TMPFILE" > /dev/null; then
         save_to="${host}/overlay/etc/hiera/data/secrets.yaml.asc"
 
 	# extract the GPG output
 	perl -e '$a = 0; while (<>) { $a = 1 if ($_ =~ /-+BEGIN PGP MESSAGE-+/);
-                 print $_ if $a; $a = 0 if ($_ =~ /-+END PGP MESSAGE-+/); }' < $TMPFILE > $TMPFILE2
+                 print $_ if $a; $a = 0 if ($_ =~ /-+END PGP MESSAGE-+/); }' < "$TMPFILE" > "$TMPFILE2"
 
-	if ! grep "END PGP MESSAGE" $TMPFILE2 > /dev/null; then
+	if ! grep "END PGP MESSAGE" "$TMPFILE2" > /dev/null; then
 	    echo "$0: Failed extracting PGP output from file $TMPFILE into $TMPFILE2"
 	    exit 1
 	fi
-    elif grep ^"STATUS=EYAML_UPDATED" $TMPFILE > /dev/null; then
-        save_to="${host}/overlay/etc/hiera/data/local.eyaml"
+    elif grep ^"STATUS=EYAML_UPDATED" "$TMPFILE" > /dev/null; then
+        if [ -n "$global" ]; then
+            save_to="${global}/overlay/etc/hiera/data/shared-cosmos.eyaml"
+        else
+            save_to="${host}/overlay/etc/hiera/data/local.eyaml"
+        fi
 
 	# extract the eyaml output
 	perl -e '$a = 0; while (<>) { $a = 1 if ($_ =~ /^---$/);
-                 print $_ if $a }' < $TMPFILE > $TMPFILE2
+                 print $_ if $a }' < "$TMPFILE" > "$TMPFILE2"
 
-	if ! grep "^---$" $TMPFILE2 > /dev/null; then
+	if ! grep "^---$" "$TMPFILE2" > /dev/null; then
 	    echo "$0: Failed extracting yaml output from file $TMPFILE into $TMPFILE2"
 	    exit 1
 	fi
@@ -155,11 +160,11 @@ function edit_copy_and_commit()
     fi
 
     # use cat to preserve permissions etc.
-    mkdir -p "`dirname ${save_to}`"
-    cat $TMPFILE2 > "${save_to}"
+    mkdir -p "$(dirname "${save_to}")"
+    cat "$TMPFILE2" > "${save_to}"
     git add "${save_to}"
 
-    if grep ^"STATUS=EYAML_UPDATED" $TMPFILE > /dev/null; then
+    if grep ^"STATUS=EYAML_UPDATED" "$TMPFILE" > /dev/null; then
 	git diff --cached "${save_to}"
     fi
 
@@ -175,17 +180,27 @@ function edit_file_on_host() {
     # Local execution on a host
     #
 
-    local SECRETFILE=/etc/hiera/data/secrets.yaml.asc
-    local EYAMLFILE=/etc/hiera/data/local.eyaml
+
+    if [ -n "$1" ]; then
+        local EYAMLFILE=/etc/hiera/data/shared-cosmos.eyaml
+        local EYAMLKEY=/etc/hiera/eyaml/shared-cosmos.pkcs7.key
+        local EYAMLPUBKEY=/etc/hiera/eyaml/shared-cosmos.pkcs7.pem
+        local SECRETFILE=/etc/hiera/data/shared-secrets.yaml.asc
+    else
+        local EYAMLFILE=/etc/hiera/data/local.eyaml
+        local EYAMLKEY=/etc/hiera/eyaml/private_key.pkcs7.pem
+        local EYAMLPUBKEY=/etc/hiera/eyaml/public_certkey.pkcs7.pem
+        local SECRETFILE=/etc/hiera/data/secrets.yaml.asc
+    fi
 
     if [ -f "${EYAMLFILE}" ]; then
-	edit_eyaml_file ${EYAMLFILE}
+        edit_eyaml_file ${EYAMLFILE} ${EYAMLKEY} ${EYAMLPUBKEY}
     elif [ -f "${SECRETFILE}" ]; then
-	edit_gpg_file ${SECRETFILE}
-    elif [ -f /etc/hiera/eyaml/public_certkey.pkcs7.pem ]; then
-	# default to eyaml if the key exists and none of the secrets-file above exist
-	echo "---" > ${EYAMLFILE}
-	edit_eyaml_file ${EYAMLFILE}
+        edit_gpg_file ${SECRETFILE}
+    elif [ -f "${EYAMLKEY}" ]; then
+    # default to eyaml if the key exists and none of the secrets-file above exist
+        echo "---" > ${EYAMLFILE}
+        edit_eyaml_file ${EYAMLFILE} ${EYAMLKEY} ${EYAMLPUBKEY}
     fi
 }
 
@@ -196,13 +211,14 @@ function edit_gpg_file()
     GNUPGHOME=/etc/hiera/gpg/
     export GNUPGHOME
 
-    local GPG=`which gpg2 || true`
+    local GPG
+    GPG=$(which gpg2 || true)
     if [ ! -x "$GPG" ]; then
-	GPG=`which gpg || true`
-	if [ ! -x "$GPG" ]; then
-	    echo "$0: gpg2 or gpg not found"
-	    exit 1
-	fi
+        GPG=$(which gpg || true)
+        if [ ! -x "$GPG" ]; then
+            echo "$0: gpg2 or gpg not found"
+            exit 1
+        fi
     fi
 
     if ! $GPG --list-secret-keys | grep -q ^"sec\s"; then
@@ -213,19 +229,19 @@ function edit_gpg_file()
 	exit 1
     fi
 
-    if [ -s $SECRETFILE ]; then
-	$GPG -d $SECRETFILE > $TMPFILE
+    if [ -s "$SECRETFILE" ]; then
+	$GPG -d "$SECRETFILE" > "$TMPFILE"
     fi
 
-    cp $TMPFILE $TMPFILE2
-    sensible-editor $TMPFILE
-    rm -f ${TMPFILE}~ ${TMPFILE2}~
+    cp "$TMPFILE" "$TMPFILE2"
+    sensible-editor "$TMPFILE"
+    rm -f "${TMPFILE}"~ "${TMPFILE2}"~
 
     echo ""
     echo ""
 
     local status=0
-    cmp -s $TMPFILE $TMPFILE2 || status=1
+    cmp -s "$TMPFILE" "$TMPFILE2" || status=1
     if [ $status -eq 0 ]; then
 	(
 	    echo "STATUS=NOT_CHANGED"
@@ -240,13 +256,13 @@ function edit_gpg_file()
 	    recipient=$($GPG --list-secret-key | grep ^sec | head -1 | awk '{print $2}' | cut -d / -f 2)
 	fi
 
-	save_to="`hostname --fqdn`/overlay${SECRETFILE}"
+	save_to="$(hostname --fqdn)/overlay${SECRETFILE}"
 	echo ""
 	(
 	    echo "STATUS=UPDATED"
 	    echo ""
 	) > $LAST_OUTPUT_FILENAME
-	$GPG --output - --armor --recipient $recipient --sign --encrypt $TMPFILE >> $LAST_OUTPUT_FILENAME
+	$GPG --output - --armor --recipient "$recipient" --sign --encrypt "$TMPFILE" >> $LAST_OUTPUT_FILENAME
 	echo ""
 	echo "GPG output saved in $LAST_OUTPUT_FILENAME - save it in Cosmos as"
 	echo ""
@@ -259,11 +275,10 @@ function edit_eyaml_file()
 {
     local EYAMLFILE=$1
 
-    local FQDN=$(hostname --fqdn)
-    local privkey='/etc/hiera/eyaml/private_key.pkcs7.pem'
-    local pubkey='/etc/hiera/eyaml/public_certkey.pkcs7.pem'
+    local privkey=$2
+    local pubkey=$3
     for f in $privkey $pubkey; do
-	test -f "${f}" || { echo "$0: eyaml key file ${f} not found"; exit 1; }
+        test -f "${f}" || { echo "$0: eyaml key file ${f} not found"; exit 1; }
     done
 
     patch_broken_eyaml
@@ -273,7 +288,7 @@ function edit_eyaml_file()
     eyaml edit --pkcs7-private-key "${privkey}" --pkcs7-public-key "${pubkey}" "${EYAMLFILE}"
 
     local status=0
-    cmp -s "${EYAMLFILE}" $TMPFILE || status=1
+    cmp -s "${EYAMLFILE}" "$TMPFILE" || status=1
     if [ $status -eq 0 ]; then
 	(
 	    echo "STATUS=NOT_CHANGED"
@@ -292,16 +307,23 @@ function edit_eyaml_file()
 
 
 if [[ $1 == '--on-host' ]]; then
-    edit_file_on_host
+    edit_file_on_host "$2"
 else
-    host=$(echo $1 | sed -e 's!/*$!!')    # remove trailing slashes
+    host=${1/%\/*/}    # remove trailing slashes
+    global=false
+    if [ -n "$2" ]; then
+        if [ ! -d "$2/overlay/etc/hiera/data/" ]; then
+            echo "Overlay folder is not configured with hiera $2/overlay/etc/hiera/data/"
+            exit 2
+        fi
+    fi
 
-    if [ ! -d $host ]; then
+    if [ ! -d "$host" ]; then
 	echo "$0: No host-directory for '$host' found - execute in top-level cosmos dir"
 	exit 1
     fi
 
-    edit_copy_and_commit $host
+    edit_copy_and_commit "$host" "$2"
 fi
 
 exit 0
