Consistency
Initial commit of `shfmt` and `shellcheck`. More to come.

diff --git a/global/post-tasks.d/014set-cosmos-permissions b/global/post-tasks.d/014set-cosmos-permissions
--- a/global/post-tasks.d/014set-cosmos-permissions
+++ b/global/post-tasks.d/014set-cosmos-permissions
@@ -11,13 +11,13 @@ set -e
 self=$(basename "$0")
 
 if ! test -d "$COSMOS_BASE"; then
-    test -z "$COSMOS_VERBOSE" || echo "$self: COSMOS_BASE was not found. Aborting change of permissions."
-    exit 0
+	test -z "$COSMOS_VERBOSE" || echo "$self: COSMOS_BASE was not found. Aborting change of permissions."
+	exit 0
 fi
 
 args=""
 if [ "x$COSMOS_VERBOSE" = "xy" ]; then
-    args="-v"
+	args="-v"
 fi
 
 chown ${args} root:root "$COSMOS_BASE"
